### ISSUE TITLE
Unable to edit files

### ISSUE THREAD

**Issue by vanj** [foex-open-source/apex-builder-extension-by-fos#10]
Chrome 84.0.4147.105 (Official Build) (64-bit) on Windows 10
APEX 20.1

Installed the extension and navigated to Application > Shared Components > Static Application Files

Picked a JS file from the Open File dropdown. Got a blank pane and the following error in the browser console

Please advise. Thanks

require.js?v=20.1.0.00.13:5 Uncaught (in promise) Error: Mismatched anonymous define() module: function(){return{js_beautify:e}}
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js?v=20.1.0.00.13:5)
    at T (require.js?v=20.1.0.00.13:5)
    at Object.s [as require] (require.js?v=20.1.0.00.13:5)
    at requirejs (require.js?v=20.1.0.00.13:5)
    at Function.req.config (require.js?v=20.1.0.00.13:5)
    at bundle.js:31997
    at new Promise (<anonymous>)
    at _callee$ (bundle.js:31996)
    at tryCatch (bundle.js:58)
    at Generator.invoke [as _invoke] (bundle.js:287)
makeError @ require.js?v=20.1.0.00.13:5
T @ require.js?v=20.1.0.00.13:5
s @ require.js?v=20.1.0.00.13:5
requirejs @ require.js?v=20.1.0.00.13:5
req.config @ require.js?v=20.1.0.00.13:5
(anonymous) @ bundle.js:31997
_callee$ @ bundle.js:31996
tryCatch @ bundle.js:58
invoke @ bundle.js:287
prototype.<computed> @ bundle.js:110
asyncGeneratorStep @ bundle.js:749
_next @ bundle.js:771
(anonymous) @ bundle.js:778
(anonymous) @ bundle.js:767
init @ bundle.js:32026
_callee$ @ bundle.js:32194
tryCatch @ bundle.js:58
invoke @ bundle.js:287
prototype.<computed> @ bundle.js:110
asyncGeneratorStep @ bundle.js:749
_next @ bundle.js:771
(anonymous) @ bundle.js:778
(anonymous) @ bundle.js:767
init @ bundle.js:32255
_onNewContainerCreate @ bundle.js:37984
(anonymous) @ bundle.js:37897
lm.items.Component @ bundle.js:36055
createContentItem @ bundle.js:33191
_$normalizeContentItem @ bundle.js:33494
addChild @ bundle.js:36830
_callee7$ @ bundle.js:38166
tryCatch @ bundle.js:58
invoke @ bundle.js:287
prototype.<computed> @ bundle.js:110
asyncGeneratorStep @ bundle.js:749
_next @ bundle.js:771
Promise.then (async)
_onNewContainerCreate @ bundle.js:37984
(anonymous) @ bundle.js:37897
lm.items.Component @ bundle.js:36055
createContentItem @ bundle.js:33191
_$normalizeContentItem @ bundle.js:33494
addChild @ bundle.js:36830
_callee7$ @ bundle.js:38166
tryCatch @ bundle.js:58
invoke @ bundle.js:287
prototype.<computed> @ bundle.js:110
asyncGeneratorStep @ bundle.js:749
_next @ bundle.js:771
Promise.then (async)
asyncGeneratorStep @ bundle.js:759
_next @ bundle.js:771
(anonymous) @ bundle.js:778
(anonymous) @ bundle.js:767
_openFileEditor @ bundle.js:38183
openFileEditor @ bundle.js:37907
_callee8$ @ bundle.js:38235
tryCatch @ bundle.js:58
invoke @ bundle.js:287
prototype.<computed> @ bundle.js:110
asyncGeneratorStep @ bundle.js:749
_next @ bundle.js:771
(anonymous) @ bundle.js:778
(anonymous) @ bundle.js:767
dispatch @ desktop_all.min.js?v=20.1.0.00.13:2
v.handle @ desktop_all.min.js?v=20.1.0.00.13:2
ListPicker._handleMouseUp
Show 6 more frames

**Comment by stefandobre** [comment]
Are you using any other browser extensions that might influence this page, i.e. insert any other scripts?

**Comment by vanj** [comment]
I have the following APEX related extensions
https://chrome.google.com/webstore/detail/apex-page-designer-tab-lo/epenpjchljckbcfcmlahbhldaibgeolm
https://chrome.google.com/webstore/detail/insum-apex-pro/mjioniifffnmbdkkfmfjeclkpghlpmai
https://chrome.google.com/webstore/detail/smart4solutions-apex-plug/lgmmnahldjoppnjcbfacinccelajclnh

By disabling them one by one, I found that the last one (SMART4Solutions - APEX Plugin) interferes with your extension. 

Any ideas on how to proceed?

**Comment by stefandobre** [comment]
I'm afraid there's not much we can do about this. There are some issues with how the other extension loads its javascript files, which upsets requirejs.

What you could do is set the extensions to only run "when the extension is clicked", and try to only have one of them enabled at a time.
