### ISSUE TITLE
Boilerplate Code regions not loading

### ISSUE THREAD

**Issue by zrh535** [foex-open-source/apex-builder-extension-by-fos#22]
Browser developer tools for both Firefox and Chrome indicate a 404 error attempting to download CodeMirror from apex.oracle.com

We are using a self-hosted APEX 21.2 environment

![image](https://user-images.githubusercontent.com/87528776/165305618-1abc5d24-2e11-4ccf-9f15-6dad29c01ab0.png)
![image](https://user-images.githubusercontent.com/87528776/165305733-fbc99777-e4b1-4052-b303-2b3a84db0fc5.png)

**Comment by foex-open-source** [comment]
Thanks for finding this one. We fixed the Boilerplate app, everything is working again.

**Comment by zrh535** [comment]
Thank you for the quick resolution!
